server:
  port: 8082
# config registry eureka
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost/escustomerdb
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
