server:
  port: 8083
# config registry eureka
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost/esfinancialdb
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user